### ISSUE TITLE
Applying forcefield  to mBuild compound

### ISSUE THREAD

**Issue by mikemhenry** [mosdef-hub/foyer#105]
I'm working on a different way to apply a force field to a mBuild compound.
```
from foyer import Forcefield
import mbuild as mb

class CH2(mb.Compound):
    def __init__(self):
        super(CH2, self).__init__()
        self.add(mb.Particle(name='C', pos=[0,0,0]), label='C[$]')
        self.add(mb.Particle(name='H', pos=[-0.109, 0, 0.0]), label='HC[$]')    
        self.add(mb.Particle(name='H', pos=[0.109, 0, 0.0]), label='HC[$]')

oplsaa = Forcefield(name='oplsaa')
ch2 = oplsaa.apply(CH2(), output_refs=True)
```

```
  File "/home/mike/miniconda3/envs/p3ht-example/lib/python3.5/site-packages/simtk/openmm/app/topology.py", line 241, in setPeriodicBoxVectors
    raise ValueError("Periodic box vectors must be in reduced form.");

```
If you adjust the the particle locations to something like
`
        self.add(mb.Particle(name='C', pos=[0,0.1,0.1]), label='C[$]')`

We get back to the error in issue #104 
So I think we are hitting an edge case since we have a 1 dimensional bounding box. I'm not sure the best way to fix it.

**Comment by ctk3b** [comment]
That's definitely a bug in mBuild, thanks for the report. I believe this will be fixed as soon as https://github.com/mosdef-hub/mbuild/pull/330 gets merged.

**Comment by ctk3b** [comment]
Sorry didn't read this closely enough. You're absolutely right about the 1-dimensional bounding box. @justingilmer is working on a fix now.
