### ISSUE TITLE
TokenizeError: Illegal character in input

### ISSUE THREAD

**Issue by mikemhenry** [mosdef-hub/foyer#106]
I'm using foyer '0.2.3' and mbuld 3072c6cf8c1.

```
import mbuild as mb
p3ht = mb.load('p3ht.pdb')
p3ht.save("p3ht.hoomdxml", overwrite=True, forcefield_name="oplsaa")
```

This works (stills fails on cabon 7 since I haven't added it yet to the force field) but in order to add the parameters I need to use my own force field file, so I copied the oplsaa.xml file and renamed it myoplsaa.xml.
```

import mbuild as mb
p3ht = mb.load('p3ht.pdb')
p3ht.save("p3ht.hoomdxml", overwrite=True, forcefield_files="oplsaa.xml")


```

This now gives me a different error:

```
/home/mike/miniconda3/envs/p3ht-example/lib/python3.5/site-packages/plyplus/engine_ply.py in t_error(t)
     20     @staticmethod
     21     def t_error(t):
---> 22         raise TokenizeError("Illegal character in input: '%s', line: %s, %s" % (t.value[:32], t.lineno, t.type))
     23 
     24     p_error = NotImplemented

TokenizeError: Illegal character in input: 'r5]1[C;X3;r5][C;X3;r5][C;X3;r5][', line: 1, error

```
I deleted the offending lines in myoplsaa.xml until I got the same "FoyerError: Found no types for atom 7 (carbon)." error.

Here is a link to the diff of the files:
http://pastebin.com/zUfLRpwN

Which is a list of every line it threw up on. I'm not sure what they all have in common/why oplsaa built in force field is parsed differently than a user supplied one. 

[p3ht.pdb.txt](https://github.com/mosdef-hub/foyer/files/865182/p3ht.pdb.txt)

**Comment by ctk3b** [comment]
Could you try installing foyer from source? I think this was fixed in https://github.com/mosdef-hub/foyer/pull/86

**Comment by mikemhenry** [comment]
Sorry I thought I tired that, must have forgotten to restart the notebook! It does work now.
