### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by mikemhenry** [mosdef-hub/foyer#109]
When using foyer, is there a paper we should site? Or just a URL to the github repo?

**Comment by ctk3b** [comment]
Github repo and perhaps this conference contribution are the best options right now. We're looking into pushing out a more appropriate citable document in the near future 

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=5mmagoEAAAAJ&citation_for_view=5mmagoEAAAAJ:TQgYirikUcIC

**Comment by mikemhenry** [comment]
Thanks!
