### ISSUE TITLE
Handling of custom cross-interactions

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/foyer#128]
As far as I can tell, there's no simple way to set cross-interactions that differ from what a combining rule would specify. In other words, I can't manually set the nonbonded interaction between atomtype i and atomtype j, which I would like to do for certain custom forcefields. I'm not sure exactly how openmm handles it (if it does) but [parmed appears to](https://github.com/ParmEd/ParmEd/blob/e4173b177f78b7321ae2cd9dd546349ec9e82754/parmed/gromacs/gromacstop.py)

**Comment by summeraz** [comment]
It appears this is doable within an OpenMM XML (see [this example](https://github.com/choderalab/openmm-forcefields/blob/57892fd64405aa72a9980c827a0c41733afcb230/charmm/ffxml/waters_ions_spc.xml#L117)). Whether or not that information would get passed through using our current workflow is another matter...

**Comment by mattwthompson** [comment]
While attempting to worth through https://github.com/mosdef-hub/mbuild/issues/455, I can say it is not supported in the current XML schema (much less passed through to the atomtyping step)

```
>>> Forcefield('nbfixpair.xml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/foyer/foyer/forcefield.py", line 230, in __init__
    Validator(ff_file_name, debug)
  File "/Users/mwt/software/foyer/foyer/validator.py", line 21, in __init__
    self.validate_xsd(ff_tree)
  File "/Users/mwt/software/foyer/foyer/validator.py", line 59, in validate_xsd
    xmlschema.assertValid(ff_tree)
  File "src/lxml/etree.pyx", line 3532, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Element 'LennardJonesForce': This element is not expected., line 13
```

in which the offending file (lines 13-15) are
```
  <LennardJonesForce lj14scale="1.0">
   <NBFixPair epsilon="0.01" sigma="0.02" type1="Ti3+4" type2="C_3"/>
  </LennardJonesForce>

**Comment by summeraz** [comment]
Right. That should just require some modifications to the [`ff.xsd` file](https://github.com/mosdef-hub/foyer/blob/ca63bef19bbec4a6e607810db2006110830b4c7c/foyer/forcefields/ff.xsd). _Then_ we'll get to see if [these lines](https://github.com/mosdef-hub/foyer/blob/ca63bef19bbec4a6e607810db2006110830b4c7c/foyer/forcefield.py#L380-L382) play along nicely.
