### ISSUE TITLE
Citing foyer?

### ISSUE THREAD

**Issue by davidlmobley** [mosdef-hub/foyer#145]
Do you guys have something we should cite for this effort yet, or just the github repo?

Thanks.

**Comment by mattwthompson** [comment]
Nothing yet, but there's a paper or two in the works.

**Comment by chrisiacovella** [comment]
There are two papers in the works, one which should hopefully be submitted soon.  For now, along with the github repo, you can cite this conference paper: 

 Iacovella, C. R.; Sallai, J.; Klein, C.; Ma, T. Idea Paper : Development of a Software Framework for Formalizing Forcefield Atom-Typing for Molecular Simulation. In 4th Workshop on Sustainable Software for Science: Practice and Experiences (WSSSPE4); 2016.

http://ceur-ws.org/Vol-1686/WSSSPE4_paper_35.pdf

We published this paper a few months ago that uses the formalism to distribute a forcefield for PFPEs:
http://pubs.acs.org/doi/abs/10.1021/acs.jpcb.7b00891

Where we used zenodo to generate a doi for the github repo that contained the forcefield and various tests (sort of our first test of using the format and software to aid in dissemination):  http://dx.doi.org/10.5281/zenodo.583310

**Comment by chrisiacovella** [comment]
We also have a poster available on Fig Share from the  SSI-SSE PI meeting.

Iacovella, Christopher; Sallai, Janos (2017): SI2-SSE: Development of a Software Framework for Formalizing ForceField Atom-Typing for Molecular Simulation. figshare.
https://doi.org/10.6084/m9.figshare.4573048.v1

And yeah, the landing page should probably be updated to reflect this info.

**Comment by davidlmobley** [comment]
Any updates on this? Maybe a preprint? :) (And would love to see the authoritative info on the landing page.)

**Comment by summeraz** [comment]
@davidlmobley Not much new to report unfortunately. However, we are prioritizing the Foyer paper, so we hope to have this completed soon. Additionally, we plan to setup a Github-hosted website for Foyer (similar to what we currently have for mBuild) that will contain a section on how to properly cite. We'll keep you posted!

**Comment by mattwthompson** [comment]
@davidlmobley just in case it hasn't come across your radar, we have a preprint up https://arxiv.org/abs/1812.06779

Added a link to our README in #202 but I'll keep this open until it's published

**Comment by davidlmobley** [comment]
Thanks, saving for my records!
