### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by chrisiacovella** [mosdef-hub/foyer#146]
We should update the landing page to reflect what we've done so far:

Conference paper

Iacovella, C. R.; Sallai, J.; Klein, C.; Ma, T. Idea Paper : Development of a Software Framework for Formalizing Forcefield Atom-Typing for Molecular Simulation. In 4th Workshop on Sustainable Software for Science: Practice and Experiences (WSSSPE4); 2016.
http://ceur-ws.org/Vol-1686/WSSSPE4_paper_35.pdf

SSI-SSE poster:
Iacovella, Christopher; Sallai, Janos (2017): SI2-SSE: Development of a Software Framework for Formalizing ForceField Atom-Typing for Molecular Simulation. figshare.
https://doi.org/10.6084/m9.figshare.4573048.v1

Forcefields:
PFAs:
https://github.com/chrisiacovella/oplsaa_perfluoroalkanes

Alkylsilane:
https://github.com/summeraz/OPLSaa_alkylsilanes

PFPEs paper:
http://pubs.acs.org/doi/abs/10.1021/acs.jpcb.7b00891

and associated PFPE forcefield:
http://dx.doi.org/10.5281/zenodo.583310

**Comment by ctk3b** [comment]
Could you just copy paste that into a PR against the README?

**Comment by mattwthompson** [comment]
I am going to close this now that our README is prettier
