### ISSUE TITLE
Forcefield.createSystem cannot accept atomtype=False

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/foyer#157]
I was messing around with `forcefield.createSystem` to see how much time is taken up by all of the steps involved `openmm.System` compared to the atomtyping step(s). I wanted to use `atomtype=False` to skip over the atomtyping but found this is not a valid argument. The [block](https://github.com/mosdef-hub/foyer/blob/master/foyer/forcefield.py?utf8=%E2%9C%93#L373) at L373 gets skipped over and the function eventually errors out at L428 when it fails to find atomtypes. This is not tested for, and from what I can tell will fail for any system lacking nonbonded parameters.

Maybe this should only be called on a `openmm.Topology` that already has the appropriate nonbonded information, but I don't see how that can happen - nowhere else in `forcefield.py` is `find_atomtypes` called. Perhaps this was saved for a future feature? I'm confused how this case could even happen if `createSystem` returns `openmm.System` and there is currently no other operation on `openmm.Topology` that would fill in that information.

We should either document this or remove `atomtype` as an argument altogether.

**Comment by mattwthompson** [comment]
Another suggestion - what if we wrap the `if Atomtype` block into a separate function?

**Comment by ctk3b** [comment]
> This is not tested for, and from what I can tell will fail for any system lacking nonbonded parameters.

Good catch. Should definitely have been tested but as you point out is a flawed concept to begin with. IIRC, in the standard openmm createSystem, this is the place where templates are applied -something we would [like to support](https://github.com/mosdef-hub/foyer/issues/80) as well. Presumably, there should be some check post atomtyping/templating to assert that all atoms have a type. If they don't, there's not enough information to build a system.

> Another suggestion - what if we wrap the if Atomtype block into a separate function?

That seems sensible regardless of the above issues. +1 from me.

**Comment by mattwthompson** [comment]
👍 I'll see if I can wrangle a PR to at least address the second point

**Comment by mattwthompson** [comment]
Resolved #159 

* Atomtyping moved into a new function

* `atomtype` removed as an argument to `Forcefield.createSystem`
