### ISSUE TITLE
Incorrect atom typing?

### ISSUE THREAD

**Issue by mikemhenry** [mosdef-hub/foyer#170]
You will need to remove the extra .txt on these files.
[pc71bm.hoomdxml.txt](https://github.com/mosdef-hub/foyer/files/2073145/pc71bm.hoomdxml.txt)
[opv_ff.xml.txt](https://github.com/mosdef-hub/foyer/files/2073146/opv_ff.xml.txt)
 
```
pc71bm = mb.load("pc71bm.hoomdxml")
foyer_kwargs = {"assert_angle_params": False,
                "assert_dihedral_params": False}
pc71bm.save("pcbm_box_other.hoomdxml", forcefield_files="opv_ff.xml", overwrite=True, foyer_kwargs=foyer_kwargs)
```
The C atoms in the rings should be CA, and the other C atoms should be typed CT.

**Comment by mikemhenry** [comment]
![image](https://user-images.githubusercontent.com/11765982/40990179-354a727c-68ad-11e8-8e02-982de2e89023.png)

With def="C[r6,r5]" it looks like only one atom is being miss typed

**Comment by summeraz** [comment]
I think the issue is with the ring-finding, specifically with the use of NetworkX's [`cycle_basis`](https://github.com/mosdef-hub/foyer/blob/6b61e9de709d43ddad0f63e06543f5a4b3f91f38/foyer/smarts_graph.py#L259). My guess is that for multi-cyclic systems like a fullerene, a valid cycle basis could be returned that does not include all of the rings in the system.

**Comment by summeraz** [comment]
I _think_ `cycle_basis` should be replaced with something [like this](https://gist.github.com/joe-jordan/6548029), but would likely increase the time of atomtyping considerably...

**Comment by mikemhenry** [comment]
I can take a look at implementing that, but in the mean time do you have any ideas for how I can type the system as a work arround?

Regarding performance:
Maybe I don't understand how the residue map works, but it would be nice if I could type _a_ pcbm and _a_ p3ht, then pack them into a box, and then save them. Then foryer only needs to type 2 molecules which will really improve performance.

**Comment by mattwthompson** [comment]
>Then foryer only needs to type 2 molecules which will really improve performance.

That's the expected behavior if the residue map is used. The only caveat is that it looks are residue names *only*. So if your molecules are separate residues with identical names, it should be taking advantage of the residue map.

**Comment by mikemhenry** [comment]
How do I set the residue name? I didn't see that as a compound attribute.

**Comment by mikemhenry** [comment]
> Residues are assigned by checking against Compound.name.
RTFM mike.

**Comment by mattwthompson** [comment]
Residues aren't explicitly accounting for in `mb.Compound`. I would recommend converting it to a `parmed.Structure` first (`mycompound.to_parmed(residues=['myresname_a', 'myresname_b'])`). `foyer` does that conversion [internally](https://github.com/mosdef-hub/foyer/blob/master/foyer/forcefield.py#L96) but it not guaranteed to interpret the hierarchy the way you would want it to.

**Comment by mikemhenry** [comment]
Oh so can I not do a `self.name = "pcbm"` or a` pcbm.name = "pcbm"` to set the name?

**Comment by mattwthompson** [comment]
If your hierarchy is relatively simple, that should work.

**Comment by mikemhenry** [comment]
```
"""forked from networkx dfs_edges function. Assumes nodes are integers, or at least
    types which work with min() and > ."""

"""cycle as a tuple in a deterministic order."""
```

These doc strings in that example code you linked to @summeraz  I think hint at the problem, we need a deterministic way to walk  through the cycle. I haven't really done any work with networkx, but could we use the atom index?

**Comment by summeraz** [comment]
That could work. I don't actually think it should matter what node the cycle-finding starts with. If our goal is to find all of the cycles containing ≤ 8 particles that a given particle is within, then the atomtyping can be deterministic even if networkx isn't.

**Comment by mikemhenry** [comment]
That PR fixes all the ring stuff, but I do have another question, how can I get the carbon that is connected to the tail of carbons, the top ring, and the fullerene cage, typed as CT? I'm not sure how it is getting typed as a CA since it isn't in a 5 or 6 ring.

**Comment by summeraz** [comment]
Hmm, with the changes from #171, when I atom-type your system that bridging carbon is properly typed as CT:
[viz.pdf](https://github.com/mosdef-hub/foyer/files/2099110/viz.pdf)

**Comment by summeraz** [comment]
In your force field file you'll need to change the SMARTS for CA to `[C;r5,r6]`. Then the atom-typing should proceed as expected.

**Comment by mikemhenry** [comment]
Sweet! Thanks so much, that fixed it. So does that string mean carbon in a ring of 5 elements or in a ring of 6 elements? Did `C[r5,r6] `mean something like carbon (bonded?) to any element in a ring of 5 elements or a ring of 6 elements?

**Comment by mattwthompson** [comment]
Just to add in case it's useful,`r` indicates being in a ring of a given size but `R` can be used to indicate membership in a number of rings.

https://github.com/mosdef-hub/foyer/blob/master/foyer/smarts.py#L29
