### ISSUE TITLE
Migrate from plyplus to another parser

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/foyer#172]
https://github.com/erezsh/plyplus:

>PlyPlus is now under maintenance only.
> Please check out my new parsing library: https://github.com/erezsh/lark

What this amounts to is the lack of a Python 3.6 release on conda.

I have only touched this portion of the code now, but it looks like it should be a simple switch

https://github.com/mosdef-hub/foyer/blob/b5bf96356c40069f110a907a749be6fb6ed62415/foyer/smarts.py#L80

**Comment by mattwthompson** [comment]
On second thought, it looks like we're hosting the `plyplus` binaries ourselves. I haven't done that before but we could alternatively just add these Python 3.6 binaries.

Similar story in https://github.com/mosdef-hub/mbuild/pull/435

**Comment by ctk3b** [comment]
Would be interesting to try. Rewriting the grammar might be none trivial but we really should put in some work to get to full SMARTS feature parity anyways...

**Comment by ctk3b** [comment]
> it looks like we're hosting the plyplus binaries ourselves. I haven't done that before but we could alternatively just add these Python 3.6 binaries.

This is fairly straight forward and I would recommend this to unblock https://github.com/mosdef-hub/mbuild/pull/435. I believe @justinGilmer and @summeraz have both done it before

**Comment by justinGilmer** [comment]
We have now migrated to `lark-parser`. Its from the same developer as `plyplus`, but is being actively supported. h/t to @volgy for converting this grammar into a `lark` approved syntax.
