### ISSUE TITLE
Should foyer skip an empty def field?

### ISSUE THREAD

**Issue by mikemhenry** [mosdef-hub/foyer#179]
In order to make a foyer force field file more template-y I propose that foyer should skip an empty def field.   

`<Type name="opls_001" class="C" element="C" mass="12.0107" def="" desc="" doi=""/>`

That way it suggests to someone looking at this file that: 

1. `opls_001` is missing a `def`
1. This file is obviously a foyer force field file
1. The empty fields should be filled in 

I'd be interested in hearing the cos for this. We can keep the current behavior where a type missing an `def` is ignored, but this would make things more explicit.

Thoughts?

I was thinking the logic could be added here:
https://github.com/mosdef-hub/foyer/blob/master/foyer/forcefield.py#L329-L330

But I'm not super familiar with foyer so if we decide to do this I might need some guidance in writing the PR.

**Comment by summeraz** [comment]
I like this idea and I think you've identified the right location in the code. This might be as simple then as just adding some additional logic to that `if` statement to make sure the string is not empty.

**Comment by mattwthompson** [comment]
I think this would be an improvement. It would be nice if it was explicit that an empty `def` is different than a missing comment (`desc`, `doi`), though the user would figure it out eventually when the atomtypes are missing. I'm not sure if this function would get triggered?

https://github.com/mosdef-hub/foyer/blob/master/foyer/validator.py?utf8=%E2%9C%93#L118

**Comment by ctk3b** [comment]
I also support this. We are already parsing the value of `def` to ensure that it is a valid SMARTS string so you should only have to check if it is non-empty as @summeraz mentioned.
