### ISSUE TITLE
Pin `networkx` dependency to >= 2.0

### ISSUE THREAD

**Issue by summeraz** [mosdef-hub/foyer#183]
This is related to a problem @rmatsum836 was having related to [this line](https://github.com/mosdef-hub/foyer/blob/71fd9d65d7105254c1b5d67cc9c6f2e473d6f0a3/foyer/smarts_graph.py#L248) in `smarts_graph.py`. `networkx` changed the syntax for iterating over the nodes of a graph from `Graph.nodes_iter()` in version 1 to `Graph.nodes` in version 2. We addressed these changes in #148, but did not pin our dependency on `networkx` to version 2, so attempting to use Foyer with an older `networkx` version leads to errors.

**Comment by mattwthompson** [comment]
Closed via #210
