### ISSUE TITLE
graph-tool vs networkx

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/foyer#209]
I can't find an issue, but in the past we discussed [graph-tool](https://graph-tool.skewed.de/) as a performant alternative to networkx (see https://graph-tool.skewed.de/performance) but couldn't do much with it because it wasn't on conda. Now it looks like somebody is hosting it, so migrating would be possible.

https://anaconda.org/ostrokach-forge/graph-tool

**Comment by justinGilmer** [comment]
Currently, `graph-tool` seems to only be conda install-able on Linux. At the moment, trying to use this different api to achieve the same results from `networkx` is not worth it. If the performance gains do prove to be non-negligible, we can look at this again.
