### ISSUE TITLE
Mark some tests as flaky

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/foyer#211]
We often have cron or PR jobs fail due to little things like a network hangup or random weird travis issues (see this from this morning, in which the entire project gets a red badge because a single DOI test failed: https://travis-ci.org/mosdef-hub/foyer/builds/500469282, or the history https://travis-ci.org/mosdef-hub/foyer/builds). Restarting jobs is fine, but it would be nice to avoid this altogether. The badge will probably turn green tomorrow when the next cron jobs run, but it should be green now. I believe marking these tests as flaky is the right approach, @mikemhenry @justinGilmer?

**Comment by ctk3b** [comment]
In general, the test suite should not be making network calls. You should be mocking out the request in the test suite using something like this:
https://requests-mock.readthedocs.io/en/latest/pytest.html

Definitely not necessary here but if you find yourself mocking out lots of requests you can reach for something heavier like this: https://github.com/kevin1024/vcrpy

**Comment by mikemhenry** [comment]
I think we should mock stuff, and then keep in the real network tests but just mark them as flaky, so they can still be tested/catch issues, but won't stop things from passing.

**Comment by umesh-timalsina** [comment]
Despite #276, took into account the changed `crossref` api, tests are failing. Should create mock objects to test when handling the tests. Make sure that the functions using this retry the `request.get`, before giving up.
