### ISSUE TITLE
Output (just) atom-typing results 

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/foyer#233]
Foyer kinda squishes two steps: determining appropriate atom types and parametrizing a system according to those types. Paul Saxe today suggested it would be useful for these two steps to be more distinct. I'm not quite sure how this would be implemented but I think it's a good idea and would be a step toward making foyer have a more distinct API from mbuild and other packages.

**Comment by ahy3nz** [comment]
As it stands now, after [atomtyping is run](https://github.com/mosdef-hub/foyer/blob/2f4493d457c7d745b4654c2523e5617710203889/foyer/forcefield.py#L390), the `omm.Topology` contains atoms whose properties are `blacklist, bond_partners, element, id, index, name, residue, whitelist`, where `id` (a string) is the decided-atomtype after resolving atomtypes.

As for implementation, I wonder if the most intuitive thing is to return a dictionary whose keys are either `omm.Atom`, `pmd.Atom`, `mb.Compound/Particle`, and values are strings corresponding to the atom type?

**Comment by ctk3b** [comment]
We could remove whitelist and blacklist from the atoms and just operate on a mapping:

```
{
  id: {
    whitelist: [],
    blacklist: [],
    atomtype: the_final_type,
  ...
}
```

Then that mapping IS the output of the atomtyping step and you can just slap it onto the actual atom models. This would also avoid polluting the topology models with atomtyping specific, arguably temporary fields

**Comment by justinGilmer** [comment]
This has been taken care of by #249
