### ISSUE TITLE
Add overrides to xml_writer

### ISSUE THREAD

**Issue by ahy3nz** [mosdef-hub/foyer#240]
**Describe the behavior you would like added to Foyer**
The current xml_writer does not print out the overrides. This is an important feature to include. If a system has aliphatic alkenes and aromatic alkenes, the aromatic alkene may satisfy both the aliphatic alkane and aromatic alkene atomtype definitions - overrides would be necessary to resolve the atom type

**Describe the solution you'd like**
Similar logic as [here](https://github.com/mosdef-hub/foyer/blob/4787e68d45466e8aec19a4f99db07c65f1ebfd8e/foyer/xml_writer.py#L81)
A very simple line like `('overrides', 'forcefield.atomTypeOverrides[name]')` might be all that is necessary, and then some string-formatting to look nice in the XML

**Describe alternatives you've considered**
For some systems in which there aren't likely to be clashes, this probably won't be a problem. But it seems important to be able to use whitelists/blacklists/overrides

**Additional context**

**Comment by uppittu11** [comment]
Looks like this was fixed
