### ISSUE TITLE
NetworkX latest update causes issues

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/foyer#279]
**Bug summary**
Was reviewing [this PR in mBuild](https://github.com/mosdef-hub/mbuild/pull/618) and noticed a lot of failures in the tests.

Turns out it was due to Foyer and the [SMARTS Graph](https://travis-ci.org/mosdef-hub/mbuild/jobs/599163797).

[NetworkX recently updated to 2.4 and  the way we access nodes have been removed: `G.node –> use G.nodes`](https://networkx.github.io/documentation/stable/release/release_2.4.html)

**Code to reproduce the behavior**

Updated to networkX 2.4 and run foyer tests that use SMARTS graphs.

It appears that we just have to change from `G.node` to `G.nodes`.

**Comment by uppittu11** [comment]
Good catch! I was wondering why CI was failing

**Comment by mikemhenry** [comment]
Lets keep this issue open even post PR until we get the networkx pin sorted out.

**Comment by jennyfothergill** [comment]
has this pin been sorted out?

**Comment by justinGilmer** [comment]
It has!
