### ISSUE TITLE
Neglecting mixing rules

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/foyer#284]
**Bug summary**

Currently, no part of a `Forcefield.apply` call touches the combining rule. It is not encoded in the XML, it is not dealt with in the typing or parametrization step, and it is not considered when preparing the final structure. The default mixing rule in ParmEd is Lorentz-Berthelot, which is about as reasonable as any, but it not what is specified in the canonical [OPLS-AA paper]:(https://pubs.acs.org/doi/10.1021/ja9621760)

![image](https://user-images.githubusercontent.com/7935382/67530572-1ed6fd00-f685-11e9-91d1-1d2638b0d5e4.png)

To fix this, I propose the following two steps:

1. For the short term, we manually set the returned structure to use a geometric rule. This can easily be changed later by the user (it's just an attribute of the structure) but given that most of the user base uses OPLS-AA, I believe this is a necessary. One could argue that it is backwards-breaking in a sense, but the "backwards" part of this is wrong, so I think it should be broken. I have a PR that implements this idea.

2. A simple short-term option would be to implement #153 so that we can do something like `if self.name == 'oplsaa': structure.combining_rule = 'geometric'`

3. A better fix altogether would be to encode the mixing rule as (optional) metadata in the XML schema. This could be straightforward if we just leave it as metadata (more or less a string carried through from the header of the XML to the returned structure) or more intricate if we want to deal with the guts of OpenMM, i.e. if we want to let the user set arbitrary combining rules.

**Code to reproduce the behavior**

Any current toy tests will produce a structure with `.combining_rule == 'lorentz'` and will produce, for example, a GROMACS topology file with this in the header (2 is Lorentz-Berthelot, 3 is geometric):
```
[ defaults ]    
; nbfunc        comb-rule       gen-pairs       fudgeLJ fudgeQQ    
1               2               no              1           0.5    
```

**Software versions**

- Which version of Foyer are you using? All versions of foyer ever :)
- Which version of Python (`python --version`)? Everything
- Which operating system? Same

**Comment by ahy3nz** [comment]
FWIW, we never check if the combining rule is ever correct. When we test opls, we just atomtype and confirm the atomtypes were found correctly, but nothing else about parameters/forcefield information
