### ISSUE TITLE
Visualize results of foyer atomtyping

### ISSUE THREAD

**Issue by ahy3nz** [mosdef-hub/foyer#287]
**Describe the behavior you would like added to Foyer**
Similar to how we can visualize the mbuild bond graph, visualize the mbuild compound hierarchy, or even use nglwidgets to interact with a compound can we visualize the results of foyer atomtyping? 

**Describe the solution you'd like**
Create something like a figure/plot or jupyterwidget that shows your particles, their atomtypes, indicies, atomnames, elements? At the very least, show the particles and the atomtypes

**Describe alternatives you've considered**
I'm leaning toward a jupyterwidget because a "static" matplotlib plot might be less helpful than being able to highlight/select molecules?

**Additional context**
@umesh-timalsina you did the work for both methods of visualization, interested to hear what you think/suggest

**Comment by umesh-timalsina** [comment]
I would certainly lean towards `js` based visualization(For the sake of interactivity). If visualization has not to rely on any external molecular visualization library `NGL` or `Py3DMol` i.e. write our own generic visualization based on our data structures, then that's an interesting pursuit. If we want `matplotlib` style visualization, I have been toying around with [plotly](https://plot.ly/python/), which seems a little fancy for lack of a better word.

**Comment by mattwthompson** [comment]
For inspiration: https://smartsview.zbh.uni-hamburg.de

**Comment by daico007** [comment]
Now handled in GMSO
