### ISSUE TITLE
Read the docs builds are failing

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/foyer#318]
Read the docs builds for foyer are failing due to excessive memory usage.
The problem right now is we are building with conda environment with openmm installed. If somebody has a way around please propose it here. The latest build can be found here.
https://readthedocs.org/projects/foyer/builds/10463577/

**Comment by mattwthompson** [comment]
You can grab a recent enough `ParmEd` from[`PyPi`](https://pypi.org/project/ParmEd/) 

Although I'm not sure how much that will help, if installing `OpenMM` from conda will still pull in a top of deps ....

**Comment by umesh-timalsina** [comment]
I did try to mock openmm. I guess mocking openmm will not work because we need the actual Forcefield class from openmm. Is `openmm` available in PyPi?

**Comment by mattwthompson** [comment]
It's technically there, but it's 7 major releases and 6 years out of date, so probably not a good choice

https://pypi.org/project/openmm/#history

**Comment by umesh-timalsina** [comment]
I have sent an email to rtd support requesting increase in resources. Foyer docs build are failing for now.

**Comment by umesh-timalsina** [comment]
RTD support has increased memory to use upto 1.5GB. The builds are now passing
