### ISSUE TITLE
Error when `verbose=True` for Periodic Dihedrals

### ISSUE THREAD

**Issue by rmatsum836** [mosdef-hub/foyer#326]
**Bug summary**

This was reported back in #323 but currently `verbose=True` fails when a system with only periodic dihedrals is atom-typed.  The reason for this is that `verbose` only checks for rb torsions.  This code attempts to love over `structure.rb_torsions` which has a length of 0, so the `pmd_ids` variable never gets set.  Thus the error occurs when the print statement attempts to call` pmd_ids`.

I don't think this issue is going to be fully solved as long as ParmEd is our backend, but I think we should at least prevent the atom typing step from failing if `verbose==True`

**Code to reproduce the behavior**

Error message: ```UnboundLocalError: local variable 'pmd_ids' referenced before assignment```

**Possible solutions**

1. Continue only looping through structure.rb_torsions, but have a try, except statement when printing out missing propers

```
try:
    print('missing proper with ids {}'.format(pmd_ids))
except UnboundLocalError:
    print('No RB Torsions found')
```

2. Loop through BOTH `structure.rb_torsions` and proper dihedrals.  This is still kind of hacky because of the layered nature of dihedrals (In this case there are more parametrized dihedrals than system dihedrals).  As a result, a message wouldn't be printed in this case.

**Comment by chrisiacovella** [comment]
I just ran into this issue, as well.  Also the code as it is doesn't give any useful information if you aren't using RB torsions.  I'll submit a PR, but this change seems to fix it for both periodic and rb torsions:

```
    if verbose:
        for omm_ids in data.propers:
            missing_dihedral = True
            for pmd_proper in proper_dihedrals:
                pmd_ids = (pmd_proper.atom1.idx, pmd_proper.atom2.idx, pmd_proper.atom3.idx, pmd_proper.atom4.idx)
                if pmd_ids == omm_ids:
                    missing_dihedral = False
            for pmd_proper in structure.rb_torsions:
                pmd_ids = (pmd_proper.atom1.idx, pmd_proper.atom2.idx, pmd_proper.atom3.idx, pmd_proper.atom4.idx)
                if pmd_ids == omm_ids:
                    missing_dihedral = False
            if missing_dihedral:
                print("Missing dihedral with ids {} and types {}.".format(
                        omm_ids, [structure.atoms[idx].type for idx in omm_ids]))
```
