### ISSUE TITLE
Lark 0.8.6 Introduces Breaking Changes in Foyer

### ISSUE THREAD

**Issue by rmatsum836** [mosdef-hub/foyer#339]
**Bug summary**

Detailed in #337, Lark-parser version `0.8.6` was released this week and caused breaking changes in foyer.  Upon some investigation this is the PR, rewriting the method that iterates through subtrees is the culprit:  https://github.com/lark-parser/lark/pull/574/files

I'll do some further investigation to figure out why exactly this is causing problems for foyer

**Software versions**

- Which version of Foyer are you using? (`python -c "import foyer; print(foyer.version)"`)
- Which version of Python (`python --version`)? 3.7
- Which operating system? linux
- lark-parser 0.8.6

**Comment by daico007** [comment]
Fixed by #341
