### ISSUE TITLE
Convert OPLS FF to new format

### ISSUE THREAD

**Issue by ctk3b** [mosdef-hub/foyer#35]

**Comment by davidlmobley** [comment]
If you guys end up with time, I'd love to have a call to find out more about what you're up to and tell you about what we're up to with the SMIRFF format and SMIRKS-based chemical perception, as there may be some overlap in our efforts.

**Comment by ctk3b** [comment]
That would be great! I've been loosely following the OpenFF group repos and from what I can tell we're tackling a slightly different problem but nonetheless may have significant overlap in tooling.

We're hoping to have a more robust demo out in a week or two so maybe that would be a good ballpark timeframe to set up a chat?

**Comment by davidlmobley** [comment]
Looks like we've got a call on the books now! I think there may be some overlap in the problem space, plus I think we may have some suggestions to help you avoid some pitfalls. But I agree that things are not completely overlapping. :)

**Comment by ctk3b** [comment]
Done in #56 and #57
