### ISSUE TITLE
Found typo in code 

### ISSUE THREAD

**Issue by daico007** [mosdef-hub/foyer#359]
https://github.com/mosdef-hub/foyer/blob/12e9e6d567be321a9d977c335c9f6422af04887b/foyer/forcefield.py#L513-L514

Is this a typo in our code (should that be `desc` instead of `des`)?

**Comment by justinGilmer** [comment]
Just searched through the code base, we only use `des` here. All other instances use `desc`. This does seem to be a typo.

**Comment by daico007** [comment]
Luckily this is only a description of the atomtype so i don't think it affect any of foyer's main functions.
