### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lenaliese** [mosdef-hub/foyer#365]
Whenever I try to install foyer the following error appears. Can anyone tell me what's the problem?

(base) C:\Users\Lena>conda install -c conda-forge -c omnia -c mosdef foyer
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -

**Comment by rsdefever** [comment]
It looks like you're trying to install foyer into your base environment? What version of python do you have there? You can try creating a new environment with: conda create --name mosdef -c conda-forge -c omnia -c mosdef foyer. And then: conda activate mosdef, to activate the environment.

**Comment by lenaliese** [comment]
It works now, thank you! Mosdef is now activated. What is the simplest way to obtain OPLS-nonbondend parameter? Do I have to download openmm for that or is there a easier way? Thank you in advance!

**Comment by rmatsum836** [comment]
The OPLS parameters are contained in the foyer package as an XML file: https://github.com/mosdef-hub/foyer/blob/master/foyer/forcefields/xml/oplsaa.xml.  You will notice that not all OPLS types have been defined yet.  We are slowly working to get all of the parameters defined.  If there is a specific molecule you are studying and the atom types are not yet defined, please let us know!

Force fields in foyer are designed to be applied with a `foyer.Forcefield` object to an `mbuild.Compound` or `parmed.Structure`.  The OPLS-AA forcefield can be loaded as a `Forcefield` object by running the following in Python:
```oplsaa = foyer.Forcefield(name="oplsaa")```

As an example, we can create an `mbuild.Compound` object that represents a single methane molecule and atom-type it with foyer:
```
# initialize methane compound
methane = mb.Compound("C", smiles=True)
# initialize oplsaa force field
oplsaa = foyer.Forcefield(name="oplsaa")
# atom type oplsaa force field
typed_methane = oplsaa.apply(methane)
# save out parameters to gromacs, MoSDeF can write input files for a variety of simulation engines
typed_methane.save("methane.gro")
typed_methane.save("methane.top")
```

I would also recommend the mosdef_tutorials repo (https://github.com/mosdef-hub/mosdef_tutorials) and mosdef_workflows repo (https://github.com/mosdef-hub/mosdef-workflows) if you're interested in learning more.

**Comment by lenaliese** [comment]
Hello, I would have another question concerning the installation. Do I have to download Docker in order to 
parameterize the molecules? The Docker Installation does not work on my Computer. Where do I have to type the commands that you gave in your example? 
In my case it doesn't work to upload the forcefield in my Anaconda Prompt.

**Comment by rmatsum836** [comment]
Hi, you shouldn't have to download the docker image in order to use mBuild and foyer if you've already created a conda environment with the packages installed.  The docker image is provided as just another way in which these packages and their dependencies can be installed and used.  The above comment is code written in Python.  To make things more clear, I have taken the commands above and put them into a single python script you can run: https://gist.github.com/rmatsum836/01e1def83d709743df454a46b251f309

You can run the script by typing the following command in a terminal window: ```python build_methane.py```.

Also be sure that your conda environment is activated with `conda activate your_environment_name` or `source activate your_environment_name`.
