### ISSUE TITLE
Python 3.6 no longer supported via conda-forge

### ISSUE THREAD

**Issue by rsdefever** [mosdef-hub/foyer#371]
It appears that our migration to `conda-forge` has dropped support for `python3.6` on **macOS**:

```
conda create --name test python=3.6 foyer -c conda-forge
```

Gives:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.6
foyer -> python[version='2.7.*|3.5.*|>=2.7,<2.8.0a0|>=3.6|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
foyer -> lxml -> python[version='3.4.*|3.6.*|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.5|3.7.*']
```

Meanwhile, building `3.9.x` works just fine. Perhaps we should update the [documentation](https://foyer.mosdef.org/en/stable/installation.html#supported-python-versions) to reflect this and add `3.8/3.9` to our test matrix?

**Comment by rsdefever** [comment]
I think it is OK if we drop `Python 3.6` support (others here who are more knowledgeable, please pitch in). This looks to be numpy's suggested support:

https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule

**Comment by rsdefever** [comment]
Thanks to @umesh-timalsina this has been narrowed down.

`parmed` on `conda-forge` is only Python 3.6 - 3.9.

**Comment by mattwthompson** [comment]
You can also get `parmed` through `ambertools`, which is still being build for Python 3.6 (and likely will be until February 2022).

https://anaconda.org/conda-forge/ambertools/files
