### ISSUE TITLE
Ethane examples in documentation broken ?

### ISSUE THREAD

**Issue by bkpgh** [mosdef-hub/foyer#375]
Yesterday (1/13/2020) I cleaned out old installs of mosdef and foyer and reinstalled them in a clean conda environment, getting the versions supplied by channels omina and conda-forge. Using Python 3.7.

The ethane example here:
    https://foyer.mosdef.org/en/stable/usage_examples.html
fails on
    from mbuild.examples import Ethane
with 
    ModuleNotFoundError: No module named 'mbuild.examples' 
replacing the "from" line with "from mbuild.lib.molecules import Ethane" works.

The ethane example here:
    https://github.com/mosdef-hub/foyer
fails on 
    untyped_ethane = pmd.load_file('ethane.mol2', structure=True)
with:
OSError: ethane.mol2 does not exist
unless you separately build the .mol2 file in the local directory.

Perhaps the package directory structures have changed without the documentation keeping up?

**Comment by justinGilmer** [comment]
Hey @bkpgh , thanks for informing us of this! There have definitely been some changes that need to be updated in the documentation. 

At the moment, checkout: https://github.com/mosdef-hub/mosdef_tutorials

These tutorials and examples should be updated and will work correctly! We will get those in the documentation taken care of soon! Thank you for testing and notifying us of this!
