### ISSUE TITLE
Error: unable to apply force field to generate .top file

### ISSUE THREAD

**Issue by Mayunqiao** [mosdef-hub/foyer#380]
Apologize if there is anything I missed since I'm quite new to both mbuild and foyer. I was trying to follow tutorials to apply the force field to molecules and generate .top file. However, I got the following error:

TypeError: __init__() missing 1 required positional argument: 'topology'

I have tried a variety of ways regarding force field but they seem to all converge into the error above. For example, even the simplest form given in usage_examples.rst:

from foyer import Forcefield
oplsaa = Forcefield(name = 'oplsaa')

Or the one given in mosdef_tutorials/foyer-overview.ipynb in terms of saving the Compound into .top file:

octane.save('octane_test.top', forcefield_name='oplsaa', overwrite=True, combining_rule='geometric')

Are these tutorials not updated or am I missing anything critical? 

- Which version of Foyer are you using?: **0.7.6**
- Which version of Python?: **3.7.4**
- Which operating system?: **Windows 10**

Thanks in advance.

**Comment by daico007** [comment]
Hi @Mayunqiao, can you capture the whole error message? I tried but could not replicate the issues (I re-ran the `foyer-overview.ipynb` with foyer v0.7.6 but on a Mac and not a Window)

**Comment by Mayunqiao** [comment]
> Hi @Mayunqiao, can you capture the whole error message? I tried but could not replicate the issues (I re-ran the `foyer-overview.ipynb` with foyer v0.7.6 but on a Mac and not a Window)

Hello @daico007 , thanks for the quick reply. Here is the full error message.

TypeError                                 Traceback (most recent call last)
< ipython-input-2-6af90cd86bad > in < module >
     34 
     35 octane.save('octane_test.gro', overwrite=True)
---> 36 octane.save('octane_test.top', forcefield_name='oplsaa', overwrite=True, combining_rule='geometric')

~\Documents\Anaconda3\lib\site-packages\mbuild\compound.py in save(self, filename, show_ports, forcefield_name, forcefield_files, forcefield_debug, box, overwrite, residues, combining_rule, foyer_kwargs, **kwargs)
   1857         conversion.save(self, filename, show_ports, forcefield_name,
   1858              forcefield_files, forcefield_debug, box,
-> 1859              overwrite, residues, combining_rule, foyer_kwargs, **kwargs)
   1860 
   1861 

~\Documents\Anaconda3\lib\site-packages\mbuild\conversion.py in save(compound, filename, show_ports, forcefield_name, forcefield_files, forcefield_debug, box, overwrite, residues, combining_rule, foyer_kwargs, **kwargs)
    826             forcefield_files=forcefield_files,
    827             name=forcefield_name,
--> 828             debug=forcefield_debug
    829         )
    830 

~\Documents\Anaconda3\lib\site-packages\foyer\forcefield.py in __init__(self, forcefield_files, name, validation, debug)
    400         if validation:
    401             for ff_file_name in preprocessed_files:
--> 402                 Validator(ff_file_name, debug)
    403         try:
    404             super(Forcefield, self).__init__(*preprocessed_files)

~\Documents\Anaconda3\lib\site-packages\foyer\validator.py in __init__(self, ff_file_name, debug)
     31             # basics have been validated.
     32             from foyer.forcefield import Forcefield
---> 33             self.smarts_parser = Forcefield(preprocessed_ff_file_name, validation=False).parser
     34         finally:
     35             for ff_file_name in preprocessed_ff_file_name:

~\Documents\Anaconda3\lib\site-packages\foyer\forcefield.py in __init__(self, forcefield_files, name, validation, debug)
    415 
    416         self.parser = smarts.SMARTS(self.non_element_types)
--> 417         self._SystemData = self._SystemData()
    418 
    419     @property

TypeError: __init__() missing 1 required positional argument: 'topology'

**Comment by umesh-timalsina** [comment]
Hello @Mayunqiao, It looks like you are using an older version foyer with the new `openMM`. See, #369 for further details. The recourse here I would think is to install latest version of foyer or downgrade your `openMM`.

```
$ conda install -c conda-forge foyer=0.7.7
```

**Comment by Mayunqiao** [comment]
> Hello @Mayunqiao, It looks like you are using an older version foyer with the new `openMM`. See, #369 for further details. The recourse here I would think is to install latest version of foyer or downgrade your `openMM`.
> 
> ```
> $ conda install -c conda-forge foyer=0.7.7
> ```

Hello @umesh-timalsina , thanks for your help! Sorry that I'm not aware that my foyer version is not the latest. The .top file can be generated successfully now.
