### ISSUE TITLE
Standerize the use of elements using ele

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/foyer#391]
Is there a reason we are sub-classing Element from `openMM`in some avenues in the code base as well as using parmed's periodic table for inferring elements in some other avenues in the code base? It seems to me that a lot of this can be standardized using `ele`.

**Comment by daico007** [comment]
the parmed and openmm element are from the old implementation since gmso and ele does not exist. and I think we should replace them soon to eventually move away from parmed an openmm
