### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by dyukovsm** [mosdef-hub/foyer#458]
**Bug summary**
When trying to use foyer to produce a hand made molecule (files/DTPA_bis_ethylhexylamino.mol2) it gave found no types for atom error. When 22 amino acids and carboxylic acids were tested, only 1 amino acid and carboxylic acid  passed while all other amino acids failed. This suggests that the error is with oplsaa.xml file that details a possibility of carboxylic carbon to be bonded to amine carbon.

What were you trying to do and what happened instead? Please copy and paste the stack output
when building a custom molecule in structure similar to amino acids the molecule and most amino acids fail the subsequent energy minimize.
List of failed amino acids with  an error foyer.exceptions.FoyerError: Found no types for atom "N" (6), wehre "N" changes depending on molecule:
arginine, histidine, lysine, aspartic acid,  L glutamic acid, serine, threonine, asparagine, glutamine, cysteine, selenocysteine, proline, L alanine, valine, isoleucine, leucine, Methionine, Phenylalanine, Tyrosine.

List of failed amino acids and molecules with an error: fails with an error such as: foyer.exceptions.FoyerError: Found multiple types for atom 2 (6): ['opls_235', 'opls_267']. are :
files/DTPA_bis_ethylhexylamino.mol2, Tryptophan

List of passed amino acids with an exception: Exception: Parameters have not been assigned to all proper dihedrals. Total system dihedrals: 14, Parameterized dihedrals: 13. Note that if your system contains torsions of Ryckaert-Bellemans functional form, all of these torsions are processed as propers:
glycine

List of passed acids: 
acetic acid.

**Code to reproduce the behavior**
Included in the zip, short version:
import mbuild as mb
from foyer import Forcefield
import mbuild.formats.charmm_writer as mf_charmm

water_FF_file = 'files/oplsaa.xml'
water_molecule = mb.load('NCCCCC(N)C(=O)O', smiles=True) # fails lysine
water_molecule.energy_minimize(water_FF_file , steps=10**4)
water_molecule.name = 'DTPA'

water_molecule.save('DTPA_bis_ethylhexylamino.mol2', overwrite=True)#, combine='all')

Please include a code snippet that can be used to reproduce this bug.

```python
# Paste your code here
#
#
```

**Software versions**

- Which version of Foyer are you using? (`python -c "import foyer; print(foyer.version)"`)
foyer                     0.9.3 
mbuild                    0.13.0
[aminoError.zip](https://github.com/mosdef-hub/foyer/files/7080231/aminoError.zip)

- Which version of Python (`python --version`)?
python                    3.7.10
- Which operating system?
Linux ubuntu

**Comment by daico007** [comment]
I think this is just the SMARTS string field of the atomtype section of the XML hasn't been fully filled
