### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by InnocentBug** [mosdef-hub/foyer#482]
**Bug summary**

Multiple links for the tutorials are broken in the README displyed by github.

examples: 
SMARTS based atom typing: https://github.com/mosdef-hub/foyer/blob/master/docs/smarts.rst
Installation instructions: https://github.com/mosdef-hub/foyer/blob/master/docs/installation.rst
Basic usage examples: https://github.com/mosdef-hub/foyer/blob/master/docs/usage_examples.rst

Maybe more

**Code to reproduce the behavior**

Click on the links on the github page.

**Software versions**

- master

**Comment by daico007** [comment]
Thank you for bringing this to our attention! These links are updated in #484, which we hope to merge shortly.
