### ISSUE TITLE
Include DOI references for atom types in XML file

### ISSUE THREAD

**Issue by summeraz** [mosdef-hub/foyer#50]
An (optional) additional field could be added in the AtomTypes (or NonbondedForce) section of the force field XML file that includes a DOI reference for where the parameters for that atom came from.  

This would look something like:
`<Type name="opls_140" class="HC" element="H" mass="1.00800"   def="[H][C]" desc="alkane H" doi=“10.1021/ja9621760”/>`

During atomtyping, foyer could store the DOI's for each atom in the molecule and write out a text file that includes all papers that should be referenced.

This could also be extended to bonded force parameters as well.

**Comment by chrisiacovella** [comment]
I like this. Much better than a shorthand reference to a paper as a description.



On Feb 10, 2017, at 10:15 AM, Andrew Summers <notifications@github.com<mailto:notifications@github.com>> wrote:


An (optional) additional field could be added in the AtomTypes (or NonbondedForce) section of the force field XML file that includes a DOI reference for where the parameters for that atom came from.

This would look something like:
<Type name="opls_140" class="HC" element="H" mass="1.00800" def="[H][C]" desc="alkane H" doi=“10.1021/ja9621760”/>

During atomtyping, foyer could store the DOI's for each atom in the molecule and write out a text file that includes all papers that should be referenced.

This could also be extended to bonded force parameters as well.

**Comment by summeraz** [comment]
Resolved in #94
