### ISSUE TITLE
Atom typing triangular water fails

### ISSUE THREAD

**Issue by GregorySchwing** [mosdef-hub/foyer#505]
**Bug summary**

Build a triangular water.

foyer.exceptions.FoyerError: Found no types for atom 0 (8).

Example attached
[water.zip](https://github.com/mosdef-hub/foyer/files/8574583/water.zip)

**Comment by justinGilmer** [comment]
Hey @GregorySchwing can you give us some information about the versions of foyer and mbuild you used for this test case?

**Comment by GregorySchwing** [comment]
foyer                     0.11.0             pyhd8ed1ab_0    conda-forge
mbuild                    0.14.2             pyhd8ed1ab_0    conda-forge

**Comment by GregorySchwing** [comment]
I just had to use a ringed smarts def.
[opc3.xml.zip](https://github.com/mosdef-hub/foyer/files/8587148/opc3.xml.zip)
