### ISSUE TITLE
Improper dihedral coefficients in oplsaa.xml

### ISSUE THREAD

**Issue by HUANGZR86** [mosdef-hub/foyer#509]
Dear developer,

I am using the default oplsaa.xml force field with customized atom types on my molecule "CCC[S+]1CCCC1". However, all the improper dihedrals cannot be parameterized. 

![image](https://user-images.githubusercontent.com/44540970/178419456-5b622b0e-3e60-4f1d-b6b5-b78e481788cb.png)

In this case, will there be any problem with my MD simulation if these improper parameters are missing? Or how can I find and add those improper coefficients?

Can you give me some advice to deal with it?

Best wishes,
Ziru

**Comment by HUANGZR86** [comment]
More specifically, is there any symbol that stands for all atom classes in foyer, e.g. class="*", similar to the atom class 0 in the Tinker OPLSAA.prm ?

![image](https://user-images.githubusercontent.com/44540970/178439299-2f11824a-ee15-4157-a3e0-b05bb5008b70.png)

**Comment by daico007** [comment]
Usually, we only expect improper parameters for ring structure, so for the molecule you have above, that may be necessary. Unfortunately, I don't think our current `oplsaa.xml` has any impropers in it (but you can add those in to your local xml file). And to present a wildcard (that can take any atom classes), you just leave it as an empty string, for example:
```xml
<Proper class1="CA" class2="CA" class3="N" class4="" c0="8.7864" c1="0.0" c2="-8.7864" c3="0.0" c4="0.0" c5="0.0"/>
```
Here, `class4` is a wildcard.

**Comment by HUANGZR86** [comment]
Thank you very much for the reply. I am now adding the OPLSAA improper parameters from Gromacs ffbonded.itp to my xml file as:

`  
  <Improper class1="C" class2="" class3="" class4="O*" c0="87.86400" c1="0.00000" c2="-87.86400" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="C_2" class2="" class3="" class4="O*" c0="87.86400" c1="0.00000" c2="-87.86400" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="C_3" class2="" class3="" class4="O*" c0="87.86400" c1="0.00000" c2="-87.86400" c3="0.00000" c4="0.00000" c5="0.00000"/>

  <Improper class1="NO" class2="NO" class3="ON" class4="" c0="87.86400" c1="0.00000" c2="-87.86400" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="" class2="N2" class3="N2" class4="N2" c0="87.86400" c1="0.00000" c2="-87.86400" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="N*" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>

  <Improper class1="CM" class2="" class3="" class4="" c0="125.52000" c1="0.00000" c2="-125.52000" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="CA" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="CB" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="CN" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="CV" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="CW" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="CR" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="CK" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="CQ" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="CS" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>
  <Improper class1="C*" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>
  
 </RBTorsionForce>`

I think the improper dihedral with ids (0, 1, 8, 9) and types ['opls_135', 'opls_136', 'opls_140', 'opls_140'], which is CT-CT-HC-HC, should be able to be parameterized. However, the error message of missing dihedral still appears. Is it because I am using the RB torsion so foyer processes those improper as propers?

**Comment by HUANGZR86** [comment]
`<Improper class1="CT" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>`

**Comment by bc118** [comment]
RB torsions are regular dihedrals, not impropers, so you need to add those parameters.  This is expected because it appears you are adding atom types to the XML file.  Also, yes, the * is the wildcard symbol in the XML files.

**Comment by HUANGZR86** [comment]
Thank you for the reply. 
However, I tried the wildcards "", " ", and "*", but none of them can work. 

`  <Improper class1="*" class2="*" class3="*" class4="*" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>`
`<Improper class1=" " class2=" " class3=" " class4=" " c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>`
`<Improper class1="" class2="" class3="" class4="" c0="9.20480" c1="0.00000" c2="-9.20480" c3="0.00000" c4="0.00000" c5="0.00000"/>`
