### ISSUE TITLE
Dihedrals not found

### ISSUE THREAD

**Issue by kierannp** [mosdef-hub/foyer#516]
**Bug summary**
I am trying to type a molecule using proper dihedrals but am receiving an error saying that the dihedrals can't be found:

Exception                                 Traceback (most recent call last)
/Users/knp/projects/silk/messing.ipynb Cell 2 in <cell line: 26>()
     [22](vscode-notebook-cell:/Users/knp/projects/silk/messing.ipynb#X22sZmlsZQ%3D%3D?line=21) gly = remove_both_terminals(gly)
     [24](vscode-notebook-cell:/Users/knp/projects/silk/messing.ipynb#X22sZmlsZQ%3D%3D?line=23) charmm = Forcefield(forcefield_files='ffs/charmm_foyer/glycine.xml',debug=True, validation=True)
---> [26](vscode-notebook-cell:/Users/knp/projects/silk/messing.ipynb#X22sZmlsZQ%3D%3D?line=25) typed_gly = charmm.apply(gly,verbose=True)
     [28](vscode-notebook-cell:/Users/knp/projects/silk/messing.ipynb#X22sZmlsZQ%3D%3D?line=27) typed_gly.save('gly_test.top')
     [29](vscode-notebook-cell:/Users/knp/projects/silk/messing.ipynb#X22sZmlsZQ%3D%3D?line=28) typed_gly.save('gly_test.gro')

File ~/miniforge3/envs/mosdef/lib/python3.8/site-packages/foyer/forcefield.py:786, in Forcefield.apply(self, structure, references_file, use_residue_map, assert_bond_params, assert_angle_params, assert_dihedral_params, assert_improper_params, verbose, *args, **kwargs)
    780 typemap = self.run_atomtyping(
    781     structure, use_residue_map=use_residue_map, **kwargs
    782 )
    784 self._apply_typemap(structure, typemap)
--> 786 structure = self.parametrize_system(
    787     structure=structure,
    788     references_file=references_file,
    789     assert_bond_params=assert_bond_params,
    790     assert_angle_params=assert_angle_params,
    791     assert_dihedral_params=assert_dihedral_params,
    792     assert_improper_params=assert_improper_params,
    793     verbose=verbose,
    794     *args,
    795     **kwargs,
    796 )
...
--> 347     raise Exception(msg)
    348 else:
    349     warnings.warn(msg)

Exception: Parameters have not been assigned to all proper dihedrals. Total system dihedrals: 6, Parameterized dihedrals: 0. Note that if your system contains torsions of Ryckaert-Bellemans functional form, all of these torsions are processed as propers.
**Code to reproduce the behavior**

Please include a code snippet that can be used to reproduce this bug.

```python
import mbuild as mb
from foyer import Forcefield
gly_smiles = 'C(C(=O)O)N'

class Glycine(mb.Compound):
    def __init__(self):
        super(Glycine, self).__init__()
        glycine = mb.load(gly_smiles,smiles=True)
        self.add(glycine)
        self.name = "Glycine"
        self.amine = glycine[4]
        self.carboxyl = glycine[1]
        amine_h = [glycine[8], glycine[9]]
        carboxyl_o = [glycine[3], glycine[7]]
        self.indices = [amine_h, carboxyl_o]

def remove_both_terminals(mol):
    amine_h, carboxyl_o = mol.indices
    mol.remove(amine_h[0])
    mol.remove(carboxyl_o)
    return mol

gly = Glycine()
gly = remove_both_terminals(gly)

charmm = Forcefield(forcefield_files='ffs/charmm_foyer/glycine.xml',debug=True, validation=True)

typed_gly = charmm.apply(gly,verbose=True)

typed_gly.save('gly_test.top')
typed_gly.save('gly_test.gro')
```

**Software versions**

- Which version of Foyer are you using? (`python -c "import foyer; print(foyer.__version__)"`)
0.11.1
- Which version of Python (`python --version`)?
Python 3.8.13
- Which operating system?
macOS Monterey 12.4

**Comment by kierannp** [comment]
Here is the forcefield xml I used

`<ForceField name="Charmm_Glycene" version="0.0.1" combining_rule="geometric">
  <AtomTypes>
    <Type name="GLY-N" class="NH1" mass="14.007" element="N" def="[N;X2](H)([C;X4])" />
    <Type name="GLY-HN" class="H" mass="1.008" element="H" def="[H;X1]([N;X2])" />
    <Type name="GLY-CA" class="CT2" mass="12.011" element="C" def="[C;X4]([N;X2])([C;X2])(H)H" />
    <Type name="GLY-HA" class="HB" mass="1.008" element="H" def="[H;X1]([C;X4])" />
    <Type name="GLY-C" class="C" mass="12.011" element="C" def="[C;X2]([C;X4])(O)" />
    <Type name="GLY-O" class="O" mass="15.999" element="O" def="[O;X1]([C;X2])" />
  </AtomTypes>
  <HarmonicBondForce>
    <Bond class1="CT2" class2="C" length="0.149" k="209199.99999999997" />
    <Bond class1="CT2" class2="CT2" length="0.15300000000000002" k="186187.99999999997" />
    <Bond class1="HB" class2="CT2" length="0.10800000000000001" k="276143.99999999994" />
    <Bond class1="NH1" class2="C" length="0.1345" k="309615.99999999994" />
    <Bond class1="NH1" class2="CT2" length="0.143" k="267775.99999999994" />
    <Bond class1="NH1" class2="H" length="0.09970000000000001" k="368191.99999999994" />
    <Bond class1="O" class2="C" length="0.123" k="518815.9999999999" />
    <Bond class1="C" class2="C" length="0.1335" k="502079.9999999999" />
  </HarmonicBondForce>
  <HarmonicAngleForce>
    <Angle class1="CT2" class2="CT2" class3="C" angle="1.8849555921538759" k="435.136" />
    <Angle class1="CT2" class2="CT2" class3="CT2" angle="1.9826940302655582" k="488.2728" />
    <Angle class1="CT2" class2="NH1" class3="C" angle="2.0943951023931953" k="418.40000000000003" />
    <Angle class1="H" class2="NH1" class3="C" angle="2.1467549799530254" k="284.512" />
    <Angle class1="H" class2="NH1" class3="CT2" angle="2.0420352248333655" k="292.88" />
    <Angle class1="HB" class2="CT2" class3="C" angle="1.911135530933791" k="418.40000000000003" />
    <Angle class1="HB" class2="CT2" class3="HB" angle="2.007128639793479" k="301.248" />
    <Angle class1="NH1" class2="C" class3="CT2" angle="2.033308578573394" k="669.44" />
    <Angle class1="NH1" class2="CT2" class3="C" angle="1.8675022996339325" k="418.40000000000003" />
    <Angle class1="NH1" class2="CT2" class3="CT2" angle="1.980948701013564" k="585.76" />
    <Angle class1="NH1" class2="CT2" class3="HB" angle="1.8849555921538759" k="401.664" />
    <Angle class1="O" class2="C" class3="CT2" angle="2.111848394913139" k="669.44" />
    <Angle class1="O" class2="C" class3="H" angle="2.1240656996770992" k="418.40000000000003" />
    <Angle class1="O" class2="C" class3="NH1" angle="2.138028333693054" k="669.44" />
  </HarmonicAngleForce>
  <AmoebaUreyBradleyForce>
    <UreyBradley class1="CT2" class2="CT2" class3="CT2" d="0.2561" k="4669.344" />
  </AmoebaUreyBradleyForce>
  <PeriodicTorsionForce>
    <Proper class1="C" class2="CT2" class3="NH1" class4="C" periodicity1="1" phase1="3.141592653589793" k1="0.8368000000000001" />
    <Proper class1="CT2" class2="C" class3="NH1" class4="CT2" periodicity1="1" phase1="0.0" k1="6.694400000000001" periodicity2="2" phase2="3.141592653589793" k2="10.46" />
    <Proper class1="CT2" class2="CT2" class3="CT2" class4="CT2" periodicity1="2" phase1="3.141592653589793" k1="0.41840000000000005" periodicity2="4" phase2="0.0" k2="0.6276" periodicity3="6" phase3="3.141592653589793" k3="0.41840000000000005" />
    <Proper class1="CT2" class2="CT2" class3="NH1" class4="C" periodicity1="1" phase1="0.0" k1="7.5312" />
    <Proper class1="H" class2="NH1" class3="C" class4="CT2" periodicity1="2" phase1="3.141592653589793" k1="10.46" />
    <Proper class1="H" class2="NH1" class3="CT2" class4="C" periodicity1="1" phase1="0.0" k1="0.0" />
    <Proper class1="H" class2="CT2" class3="NH1" class4="C" periodicity1="1" phase1="0.0" k1="0.0" />
    <Proper class1="H" class2="NH1" class3="CT2" class4="CT2" periodicity1="1" phase1="0.0" k1="0.0" />
    <Proper class1="HB" class2="CT2" class3="NH1" class4="C" periodicity1="1" phase1="0.0" k1="0.0" />
    <Proper class1="HB" class2="CT2" class3="NH1" class4="H" periodicity1="1" phase1="0.0" k1="0.0" />
    <Proper class1="NH1" class2="C" class3="CT2" class4="CT2" periodicity1="1" phase1="0.0" k1="0.0" />
    <Proper class1="NH1" class2="C" class3="CT2" class4="HB" periodicity1="1" phase1="0.0" k1="0.0" />
    <Proper class1="NH1" class2="C" class3="CT2" class4="NH1" periodicity1="1" phase1="0.0" k1="2.5104" />
    <Proper class1="O" class2="C" class3="CT2" class4="CT2" periodicity1="1" phase1="0.0" k1="5.8576" />
    <Proper class1="O" class2="C" class3="CT2" class4="HB" periodicity1="1" phase1="0.0" k1="0.0" />
    <Proper class1="O" class2="C" class3="CT2" class4="NH1" periodicity1="1" phase1="0.0" k1="0.0" />
    <Proper class1="O" class2="C" class3="NH1" class4="CT2" periodicity1="2" phase1="3.141592653589793" k1="10.46" />
    <Proper class1="O" class2="C" class3="NH1" class4="H" periodicity1="2" phase1="3.141592653589793" k1="10.46" />
    
  </PeriodicTorsionForce>
  <NonbondedForce coulomb14scale="1.0" lj14scale="1.0">
    <Atom sigma="0.3296325257119256" epsilon="0.8368000000000001" type="GLY-N" charge="-0.47" />
    <Atom sigma="0.04000135244450124" epsilon="0.192464" type="GLY-HN" charge="0.31" />
    <Atom sigma="0.35814128469241635" epsilon="0.234304" type="GLY-CA" charge="-0.02" />
    <Atom sigma="0.23876085646161097" epsilon="0.117152" type="GLY-HA" charge="0.09" />
    
    <Atom sigma="0.35635948725613575" epsilon="0.46024000000000004" type="GLY-C" charge="0.51" />
    <Atom sigma="0.30290556416771536" epsilon="0.50208" type="GLY-O" charge="-0.51" />
  </NonbondedForce>
</ForceField>`

**Comment by chrisiacovella** [comment]
This isn't an issue with the Foyer code itself, rather that there are 6 dihedrals found in the molecule that haven't been found in the forcefield  xml file.  

I'll note that in some cases you may have quartets that don't require dihedral parameters (especially for CHARMM as the dihedral parameters are corrections to the 1-4 interactions not a replacement).  If that is the case, then you'd just want to modify your apply call to tell it to ignore this (i.e., raise a warning, but not throw an error):

`typed_gly = charmm.apply(gly,verbose=True, assert_dihedral_params=False)`

Bonds, angles, dihedrals, and impropers each have an associated assert flag that can be set (i.e., assert_bond_params, assert_angle_params, assert_dihedral_params, assert_improper_params).  This is especially useful as, e.g., a CG forcefield might not need to define dihedral or angle parameters or one might use fictitious bonds in mbuild to orient building blocks in the system, but not want them to be actually chemically bound.  See [the documentation about this](https://foyer.mosdef.org/en/stable/topic_guides/ffapply.html?highlight=assert_dihedral_params#applying-a-force-field)

I'm going to close this issue as it appears the code is functioning as expected, but send me a message if you have more questions.

**Comment by CalCraven** [comment]
@chrisiacovella I think there is more going on here than meets the eye. All of the missing dihedrals seem to be found in the forcefield. Additionally, the atomtyping works using the GMSO methodology:

```python
from forcefield_utilities import FoyerFFs
loader = FoyerFFs()
gmso_ff = loader.load('ffs/charmm_foyer/glycine.xml').to_gmso_ff()
from gmso.parameterization import apply
from gmso.external.convert_mbuild import from_mbuild
gmso_top = from_mbuild(gly) #object created using above recipe
apply(gmso_top, gmso_ff, identify_connections=True)
print(gmso_top.is_typed)
```

Since this seems to work properly, there seems to be something more than just missing parameters causing the openmm issues seen here. I can spend a little bit of time better showing the dihedrals in the forcefield, and the identities of the missing dihedrals.

**Comment by daico007** [comment]
`<Proper class1="O" class2="C" class3="CT2" class4="NH1" periodicity1="1" phase1="0.0" k1="0.0" />` 
I checked amn

**Comment by daico007** [comment]
I checked this XML manually and the dihedral is actually there (for example: `<Proper class1="O" class2="C" class3="CT2" class4="NH1" periodicity1="1" phase1="0.0" k1="0.0" />`), but was just not being found. This might be on the foyer side (or our use of openmm/parmed).

**Comment by kierannp** [comment]
[glycine.txt](https://github.com/mosdef-hub/foyer/files/9499219/glycine.txt)

**Comment by kierannp** [comment]
Heres the xml for this molecule

**Comment by bc118** [comment]
I added the line to the PeriodicTorsionForce and it still errors out with a missing dihedral

<Proper class1="*" class2="*" class3="*" class4="*" periodicity1="1" phase1="0" k1="0" />

**Comment by chrisiacovella** [comment]
Ah I was too quick in closing.  So this is a ParmEd issue we have run into in the past.  If the dihedral has all the phase parameters set to 0 (i.e., it doesn't modify anything), ParmEd ignores them. The check_dihedrals function does not ignore them and throws an error.

**Comment by bc118** [comment]
I added phase1="3.141592653589793" to all the ones with k1=0 and this error is the same as before, so I'm not sure this is the issue, provided this is what you meant

**Comment by chrisiacovella** [comment]
regardless of what you set phase1 to be if k1 is hero it doesn't modify it in anyway, so ParmEd ignores it.

**Comment by bc118** [comment]
OK, yeah it works if I change K=1 to K=0.0000000001 for ones with only 1 K-value

**Comment by bc118** [comment]
@chrisiacovella good call !!!

**Comment by bc118** [comment]
See the file for  K=1 to K=0.0000000001 for ones with only 1 K-value

[glycine_mod_ks_to_near_0_values.txt](https://github.com/mosdef-hub/foyer/files/9500419/glycine_mod_ks_to_near_0_values.txt)

**Comment by bc118** [comment]
This solution seems to work so I am closing this issue
