### ISSUE TITLE
Contradictory info about supported versions of Python

### ISSUE THREAD

**Issue by iGulitch** [mosdef-hub/foyer#564]
In [Supported Python Versions](https://github.com/mosdef-hub/foyer/blob/main/docs/source/getting_started/install.rst#supported-python-versions), it's written that only Python v. 3.6 and 3.7 are officially supported and that there are no guarantees for versions <=3.5 / >= 3.8. Simultaneously, in [Installation](https://github.com/mosdef-hub/foyer/blob/main/docs/source/getting_started/install.rst#installation) the environmental file `environment.yml` has the dependency `python>=3.8`.

Would you clarify, please?

**Comment by daico007** [comment]
Hi @iGulitch, thank you for catching that! Foyer is supporting Python 3.8-3.11. We will update the docs page to reflect that.

**Comment by iGulitch** [comment]
Hi @daico007 and thanks for your quick reply!
What about Python v. 3.12.3? I got this one when install Foyer just now.

**Comment by daico007** [comment]
Python 3.12 could be fine for foyer, but not some of its dependencies (mBuild/mdtraj). I would recommend using Python 3.11

**Comment by iGulitch** [comment]
Clear, thanks!
Then, from my side, I'd suggest you to double the `yml` files with environment, since a fresh installation via `git clone` with given `environment.yml` will give the latest available Python version that is 3.12.2 now. Besides, the one for Windows has the dependency `python <=3.8` unlike all other `yml` files, where it's `python >=3.8` instead.
