### ISSUE TITLE
Compatibility of `XML` files with FF of MoSDeF and LigParGen?

### ISSUE THREAD

**Issue by iGulitch** [mosdef-hub/foyer#586]
Hi, all!

Trying to use `XML` file with FF generated by **LigParGen** in **foyer**, and obviously receive an error message. Checking the fields of foyer `XML` file with OPLS-AA FF and the **LigParGen**-generated `XML` FF file via `cat <file>.xml | sed -n '/<\//p'` and obtain for **foyer** :
```
</AtomTypes>
</HarmonicBondForce>
</HarmonicAngleForce>
</RBTorsionForce>
</NonbondedForce>
</ForceField>
```
and for **LigParGen** :
```
</AtomTypes>
</Residue>
</Residues>
</HarmonicBondForce>
</HarmonicAngleForce>
</PeriodicTorsionForce>
</NonbondedForce>
</ForceField>
```
There is the clear difference.  Suppose, I remove `</Residue>` and `</Residues>`. But what remains different are `</RBTorsionForce>` from **foyer** :
`<Proper class1="Br" class2="C" class3="CB" class4="CT" c0="0.0" c1="0.0" c2="0.0" c3="0.0" c4="0.0" c5="0.0"/>`
and `</PeriodicTorsionForce>` from **LigParGen** :
`<Improper class1="C841" class2="C840" class3="C842" class4="C843" k1="0.000000" k2="10.460000" k3="0.000000" k4="0.000000" periodicity1="1" periodicity2="2" periodicity3="3" periodicity4="4" phase1="0.00" phase2="3.141592653589793" phase3="0.00" phase4="3.141592653589793"/>`
and these two clearly have different formats.

Any idea / recommendation on how to merge the **LigParGen** `XML` file into the **foyer** `XML` ?

**Comment by chrisjonesBSU** [comment]
Periodic torsion forces should work. You can see how they are used in the Foyer compatible gaff forcefield in [GAFF-Foyer](https://github.com/rsdefever/GAFF-foyer)

**Comment by iGulitch** [comment]
@chrisjonesBSU , thanks!

Indeed, periodic torsion forces don't seem to create any troubles. Yet, there are other issue, which I'm afraid aren't of your concern :)
