### ISSUE TITLE
Verification of force field files

### ISSUE THREAD

**Issue by ctk3b** [mosdef-hub/foyer#64]
* .xml schema to catch typos in attributes/tags
* run SMARTS parsing on every atomtype to catch syntactic errors
* ensure ampersands only exist in SMARTS strings, then run something like [this](http://stackoverflow.com/questions/4972210/escaping-characters-in-a-xml-file-with-python)

**Comment by mikemhenry** [comment]
For example, overrides != override. I think its fine if we want the force field file but it should at least throw a warning with an non keyword argument is passed.
