### ISSUE TITLE
More examples (including all-atom and coarse-grained FFs)

### ISSUE THREAD

**Issue by summeraz** [mosdef-hub/foyer#66]

**Comment by mikemhenry** [comment]
I'd like to see an example starting with some pdb/topology file, using foyer to generate constraints (bonds, angles, dihedrals), then generating the FF template.

**Comment by justinGilmer** [comment]
If we needed to explain the innerworkings of the atomtyper, a graphic based approach could be cool. If we just used a very simple alkane example, could give a very simple generalization how the blacklist/whitelist works, also include an example with `overrides`. Show how it iterates over the molecule and then assigns the proper forcefield parameters. 

However, this would be a pretty big undertaking to make this look presentable. Possibly for the next release?

**Comment by mikemhenry** [comment]
Something done in code would be useful for troubleshooting as well. But I think for just explaining to some one how it works, an constructed example could be done by hand.
