### ISSUE TITLE
Support for "arbitrary" functional forms of potentials

### ISSUE THREAD

**Issue by summeraz** [mosdef-hub/foyer#67]
Right now we are limited in the functional forms that ParmEd supports, which are very few.  Since we use the OpenMM format for our force fields, that should provide an avenue for supporting arbitrary functional forms, but it will be tricky to get this information stored into a ParmEd structure...

**Comment by ctk3b** [comment]
This is currently supported but only if you intend to run in OpenMM. The much (much) larger issue of converting arbitrary functional forms is something that needs to happen in ParmEd/InterMol.

But I do think we need to [document this better](https://github.com/mosdef-hub/foyer/issues/81)
