### ISSUE TITLE
Support for Charmm parameter file using GOMC style(having repulsion exponent)

### ISSUE THREAD

**Issue by msoroush** [mosdef-hub/foyer#68]
First I want to mention an issue that we found regarding generating psf file, where atom mass was not assign properly.

In addition, I would appreciate if you could add the capability to foyer forcefield reader to read 
an extra parameter in nonbonded section (repulsion exponent of LJ potential) from .xml file and generate charmm style parameter file with repulsion exponent. The difference between GOMC style and standard charmm is that all energy units are in (K), and in nonbonded section, there is additional variable for n (repulsion exponent). 

I attached a zip file including:
1- Mie potential implemented in xml
2- Example of GOMC charmm style parameter file
3- my python script to generate pdb and psf files for leaner alkane.
[UA_atom_FF.zip](https://github.com/mosdef-hub/foyer/files/783887/UA_atom_FF.zip)

**Comment by ctk3b** [comment]
Hey @msoroush, sorry it's taken so long to get to this but I believe we've fixed the issues in the script you sent (it should work if you use the most up to date foyer and mbuild master branches).

Could you sent us a more specific script that does all the parameterization that you want and what should in theory be in the final output file(s)?

**Comment by mattwthompson** [comment]
Closed via https://github.com/mosdef-hub/mbuild/pull/508; mbuild can write out a PAR file from a parmed structure
