### ISSUE TITLE
Assign residues to particles from XML

### ISSUE THREAD

**Issue by summeraz** [mosdef-hub/foyer#69]
OpenMM XML files can have a <Residue> section for assigning residues to particles.  Right now I think foyer is ignoring this section, but it would be useful to add support to assign residues based on what's specified in the <Residue> section if one is specified

**Comment by ctk3b** [comment]
The OpenMM residues section is for templates that are used to atom type systems. E.g. protein and lipid force fields have residues with atom types defined for each amino acid and each lipid they support.

That being said we should support this. 

Closing in favor of https://github.com/mosdef-hub/foyer/issues/80
