### ISSUE TITLE
Overide API

### ISSUE THREAD

**Issue by mikemhenry** [mosdef-hub/foyer#74]
I'm working on using Foyer to generate a forcefield file for PCBM. Since I'm using an all atom model, I want to use the OPLSAA forcefield file built into foyer:

`pdb_path = get_fn("/Users/mikehenry/Downloads/PCBM.pdb")`
`untyped_pcbm = pmd.load_file(pdb_path, structure=True)`
`oplsaa = Forcefield(name='oplsaa')`
`pcbm = oplsaa.apply(untyped_pcbm)`

I get an error when I apply the forcefield: 
`FoyerError: Found multiple types for atom 2 (carbon): ['opls_139', 'opls_713']`

In order to fix this I need to do some overrides, but I'm not sure if there is a way to do that on `oplsaa` just with code, or if I need to modify the `oplsaa.xml` file.

**Comment by summeraz** [comment]
I'm guessing [this](https://github.com/mosdef-hub/foyer/files/800467/PCBM.pdf) is the atom that Foyer is finding multiple types for.  Determining which atom types get precedence (and thus which overrides you need) when an atom is part of multiple functional groups gets a bit tricky.  In this case, however, my opinion would be that 'opls_713' should override 'opls_139'.  This is something you would need to change in `oplsaa.xml` (and could submit a PR while you're at it!).  The OPLS force field in Foyer is obviously fairly incomplete, so we're hoping that as users begin to use various atom types it will begin to fill out.

**Comment by mikemhenry** [comment]
I wasn't sure if there was a way to do this without editing the `oplsaa.xml` file by hand/if there was a way to do this programmatically, something like  `oplsaa.override(['opls_713'],['opls_139']`

**Comment by summeraz** [comment]
I don't think you can manually add overrides to a Forcefield object as this is intended to all be handled within the XML file.

**Comment by ctk3b** [comment]
Yeah as @summeraz said, the intention is to have this contained in the xml file. We could think about implementing an interactive prompt for resolving overrides when you're creating a new forcefield but at the end of the day all the logic is intended to be captured in the file itself.
